### ISSUE TITLE
[CLOSED] NullPointerException on initializing session with coe-0.0.5

### ISSUE THREAD

**Issue by ldcouto** [into-cps/intocps-ui#100]
<a href="https://github.com/nablc"><img src="https://avatars.githubusercontent.com/u/18675223?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [nablc](https://github.com/nablc)**
_Tuesday Apr 26, 2016 at 07:55 GMT_
_Originally opened as https://github.com/into-cps/INTO-CPS_Application/issues/18_

----

Following error is thrown on initializing session:

SCHWERWIEGEND: Communication with the client broken, or an bug in the handler code
java.lang.NullPointerException at org.intocps.orchestration.coe.httpserver.RequestProcessors.processInitialize(RequestProcessors.java:96)
at org.intocps.orchestration.coe.httpserver.RequestHandler.initialize(RequestHandler.java:204) at 
org.intocps.orchestration.coe.httpserver.RequestHandler.handleRequest (RequestHandler.java:139) 
at org.intocps.orchestration.coe.httpserver.NanoWSDImpl.serveHttp(NanoWSDImpl.java:36)
        at fi.iki.elonen.NanoWSD.serve(NanoWSD.java:861)
        at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:925)
        at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
        at java.lang.Thread.run(Unknown Source)

[wbsocket.txt](https://github.com/into-cps/INTO-CPS_Application/files/236131/wbsocket.txt)
[config.txt](https://github.com/into-cps/INTO-CPS_Application/files/236133/config.txt)

Apr 25, 2016 4:50:07 PM fi.iki.elonen.NanoHTTPD$ClientHandler run
SCHWERWIEGEND: Communication with the client broken, or an bug in the handler code java.lang.NullPointerException

Steps to reproduce:
1. start coe: coe-0.0.5-SNAPSHOT-jar-with-dependencies.jar
2. create session : http://localhost:8082/createSession with the response {"sessionId":73885}
3. open websocket on "ws://localhost:8082/attachSession/73885" is successful 
4. initialize session : http://localhost:8082/initialize/73885 throws error

**Comment by ldcouto** [comment]
<a href="https://github.com/lausdahl"><img src="https://avatars.githubusercontent.com/u/2575418?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [lausdahl](https://github.com/lausdahl)**
_Wednesday Apr 27, 2016 at 11:58 GMT_

----

I can confirm that this is indeed the case if a post to initialise is made with no post data. I added a fix that will be included in 0.0.6.

Note that 0.0.5 is an invalid version. Only 0.0.5-SNAPSHOT should exist so I assume that this refers to that version.
