### ISSUE TITLE
[CLOSED] coe-0.0.5-SNAPSHOT-jar-with-dependencies.jar cannot initialize

### ISSUE THREAD

**Issue by ldcouto** [into-cps/intocps-ui#101]
<a href="https://github.com/mpcagro"><img src="https://avatars.githubusercontent.com/u/17993540?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mpcagro](https://github.com/mpcagro)**
_Friday Apr 29, 2016 at 11:17 GMT_
_Originally opened as https://github.com/into-cps/INTO-CPS_Application/issues/19_

----

I have just tried to download the new coe-0.0.5 engine. 
When I try to initialize using the standard example:

> curl -s -H "Content-Type: n" --data @config.json http://localhost:8082/initialize

I get the following error from the COE:

```
java -jar coe_0.05.jar 
COE(Command line options: [port]

Now running on port 8082
Server started, Hit Enter to stop.

Apr 29, 2016 1:09:53 PM fi.iki.elonen.NanoHTTPD$Response send
SEVERE: Could not send response to the client
java.net.SocketException: Broken pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at fi.iki.elonen.NanoHTTPD$Response.sendBody(NanoHTTPD.java:1620)
	at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectEncoding(NanoHTTPD.java:1593)
	at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectTransferAndEncoding(NanoHTTPD.java:1583)
	at fi.iki.elonen.NanoHTTPD$Response.send(NanoHTTPD.java:1550)
	at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:960)
	at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
	at java.lang.Thread.run(Thread.java:745)
```

My "config.json" looks like this:

```
{
    "fmus":[
        "{fmu1}":"fmus/tankcontroller.fmu",
        "{fmu2}":"fmus/tank.fmu"
    ],
    "connections":{
        "{fmu1}.controller.valve":
            ["{fmu2}.tank.valve"],
        "{fmu2}.tank.level":
            ["{fmu1}.controller.level"]
    },
    "parameters":{
        "{fmu1}.controller.maxLevel":8,
        "{fmu1}.controller.minLevel":2
    },
    "algorithm":{
        "type":"fixed-step",
        "size":0.1
    }
} 
```

**Comment by ldcouto** [comment]
<a href="https://github.com/mpcagro"><img src="https://avatars.githubusercontent.com/u/17993540?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mpcagro](https://github.com/mpcagro)**
_Friday Apr 29, 2016 at 11:26 GMT_

----

I tried to change the COE log level by updating the values for log4j.properties

from:
log4j.rootLogger= TRACE, stdout, R

to:
log4j.rootLogger=ERROR, stdout, R

```
java -jar coe_0.05.jar 
COE(Command line options: [port]

 INFO [main] (CoeMain.java:30) - Checking native FMI support
DEBUG [main] (NativeFmu.java:22) - Loading library: lib/Linux-amd64/libfmuapi.so
DEBUG [main] (NativeLibraryLoader.java:36) - Extracting library from: lib/Linux-amd64/libfmuapi.so
DEBUG [main] (NativeFmu.java:27) - Loaded Library file: /tmp/jnifmuapi-Linux-amd64/libfmuapi.so
Now running on port 8082
Server started, Hit Enter to stop.

Apr 29, 2016 1:20:58 PM fi.iki.elonen.NanoHTTPD$Response send
SEVERE: Could not send response to the client
java.net.SocketException: Broken pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at fi.iki.elonen.NanoHTTPD$Response.sendBody(NanoHTTPD.java:1620)
	at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectEncoding(NanoHTTPD.java:1593)
	at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectTransferAndEncoding(NanoHTTPD.java:1583)
	at fi.iki.elonen.NanoHTTPD$Response.send(NanoHTTPD.java:1550)
	at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:960)
	at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
	at java.lang.Thread.run(Thread.java:745)
```

I do not seem to get any new information on the error, but the COE seem to load the FMU units.

**Comment by ldcouto** [comment]
<a href="https://github.com/mpcagro"><img src="https://avatars.githubusercontent.com/u/17993540?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mpcagro](https://github.com/mpcagro)**
_Friday Apr 29, 2016 at 11:31 GMT_

----

I bit of system info to allow to allow for reproduction of the error:

```
martin@mpc-ThinkPad-W530:~/COE_tester$ uname -a
Linux mpc-ThinkPad-W530 3.19.0-58-generic #64~14.04.1-Ubuntu SMP Fri Mar 18 19:05:43 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
martin@mpc-ThinkPad-W530:~/COE_tester$ java -version
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)
martin@mpc-ThinkPad-W530:~/COE_tester$ curl --version
curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smtp smtps telnet tftp 
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP
```

Please write if you need any other info from me

**Comment by ldcouto** [comment]
<a href="https://github.com/mpcagro"><img src="https://avatars.githubusercontent.com/u/17993540?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mpcagro](https://github.com/mpcagro)**
_Monday May 02, 2016 at 00:33 GMT_

----

It was hinted that  I needed call createSession to start an COE instance.
I attempted the following command before initialize:

> curl -s http://localhost:8082/createSession

and then calling:

> curl -s -H "Content-Type: application/json" --data @config.json http://localhost:8082/initialize/:73885

Where 73885 is the sessionId from createSession.
But the result seems to be the same:

```
martin@mpc-ThinkPad-W530:~/COE_tester$ java -jar coe_0.05.jar 
COE(Command line options: [port]

 INFO [main] (CoeMain.java:30) - Checking native FMI support
DEBUG [main] (NativeFmu.java:22) - Loading library: lib/Linux-amd64/libfmuapi.so
DEBUG [main] (NativeLibraryLoader.java:36) - Extracting library from: lib/Linux-amd64/libfmuapi.so
DEBUG [main] (NativeFmu.java:27) - Loaded Library file: /tmp/jnifmuapi-Linux-amd64/libfmuapi.so
Now running on port 8082
Server started, Hit Enter to stop.

May 02, 2016 2:03:04 AM fi.iki.elonen.NanoHTTPD$Response send
SEVERE: Could not send response to the client
java.net.SocketException: Broken pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at fi.iki.elonen.NanoHTTPD$Response.sendBody(NanoHTTPD.java:1620)
	at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectEncoding(NanoHTTPD.java:1593)
	at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectTransferAndEncoding(NanoHTTPD.java:1583)
	at fi.iki.elonen.NanoHTTPD$Response.send(NanoHTTPD.java:1550)
	at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:960)
	at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
	at java.lang.Thread.run(Thread.java:745)
```
So I am unable to get it working for either the 
http://overture.au.dk/into-cps/site/simulation/example.html
 or the API in the COE and I am unsure what I am missing.

I am a bit confused why the syntax are different in some cases:
like
> curl -s http://localhost:8082/result/$sessionId

and 

> curl -s -H "Content-Type: application/json" --data @config.json http://localhost:8082/initialize/:$sessionId

Why was this extra collon "\:" added  to the syntax in some cases ?

I tried to change to the following :

> curl -s -H "Content-Type: application/json" --data @config.json http://localhost:8082/initialize/$sessionId

and the following result response to the command:
`

Can not deserialize instance of java.util.LinkedHashMap out of START_ARRAY token at [Source: { "fmus":[ "{fmu1}":"fmus/tankcontroller.fmu", "{fmu2}":"fmus/tank.fmu" ], "connections":{ "{fmu1}.controller.valve": ["{fmu2}.tank.valve"], "{fmu2}.tank.level": ["{fmu1}.controller.level"] }, "parameters":{ "{fmu1}.controller.maxLevel":8, "{fmu1}.controller.minLevel":2 }, "algorithm":{ "type":"fixed-step", "size":0.1 }}; line: 1, column: 6] (through reference chain: org.intocps.orchestration.coe.json.InitializationMsgJson["fmus"])

`

I am still not able to progress to the next step of simulating

**Comment by ldcouto** [comment]
<a href="https://github.com/CThuleHansen"><img src="https://avatars.githubusercontent.com/u/3479481?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [CThuleHansen](https://github.com/CThuleHansen)**
_Monday May 02, 2016 at 13:56 GMT_

----

**CreateSession**: You need to invoke createSession and use the ID for initializeSession.
The colon is is never part of the url. Therefore this is correct: `http://localhost:8082/initialize/$sessionId`
and this is incorrect:
`http://localhost:8082/initialize/:$sessionId`

**Config.json** Your config.json is wrong (So is the one on the webpage. It will be updated tomorrow!)
Use {} after fmus instead of [] e.g. 
`"fmus":{
        "{fmu1}":"fmus/tankcontroller.fmu",
        "{fmu2}":"fmus/tank.fmu"
}
    `
instead of 
`"fmus":[
        "{fmu1}":"fmus/tankcontroller.fmu",
        "{fmu2}":"fmus/tank.fmu"
]
    `

**Comment by ldcouto** [comment]
<a href="https://github.com/mpcagro"><img src="https://avatars.githubusercontent.com/u/17993540?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mpcagro](https://github.com/mpcagro)**
_Monday May 02, 2016 at 14:04 GMT_

----

These changes seems to solve the problem.
I will do some more testing on this tomorrow.
