### ISSUE TITLE
Initialisation error of COE 0.0.4

### ISSUE THREAD

**Issue by ldcouto** [into-cps/intocps-ui#105]
<a href="https://github.com/mpcagro"><img src="https://avatars.githubusercontent.com/u/17993540?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mpcagro](https://github.com/mpcagro)**
_Monday May 02, 2016 at 13:16 GMT_
_Originally opened as https://github.com/into-cps/INTO-CPS_Application/issues/20_

----

I get the following error for the COE v 0.04, when trying to run my new FMU units:

```
java -jar coe.jar
COE(Command line options: [port]

 INFO [main] (CoeMain.java:29) - Checking native FMI support
DEBUG [main] (NativeFmu.java:22) - Loading library: lib/Linux-amd64/libfmuapi.so
DEBUG [main] (NativeLibraryLoader.java:36) - Extracting library from: lib/Linux-amd64/libfmuapi.so
DEBUG [main] (NativeFmu.java:27) - Loaded Library file: /tmp/jnifmuapi-Linux-amd64/libfmuapi.so
Now running on port 8082
 INFO [Thread-1] (CoeRequestHandler.java:355) - Using Fixed-step size calculator with size = 0.001
java.lang.NullPointerException
	at org.intocps.orchestration.coe.httpserver.Response.<init>(Response.java:58)
	at org.intocps.orchestration.coe.json.CoeRequestHandler.processInitialize(CoeRequestHandler.java:427)
	at org.intocps.orchestration.coe.json.CoeRequestHandler.handleRequest(CoeRequestHandler.java:145)
	at org.intocps.orchestration.coe.json.CoeRequestHandler.doPost(CoeRequestHandler.java:70)
	at org.intocps.orchestration.coe.httpserver.NanoHTTPDJson$HTTPSession.processRequest(NanoHTTPDJson.java:335)
	at org.intocps.orchestration.coe.httpserver.NanoHTTPDJson$HTTPSession.run(NanoHTTPDJson.java:302)
	at java.lang.Thread.run(Thread.java:745)
ERROR [Thread-1] (CoeRequestHandler.java:439) - Initialization faild
java.lang.NullPointerException
	at org.intocps.orchestration.coe.httpserver.Response.<init>(Response.java:58)
	at org.intocps.orchestration.coe.json.CoeRequestHandler.processInitialize(CoeRequestHandler.java:427)
	at org.intocps.orchestration.coe.json.CoeRequestHandler.handleRequest(CoeRequestHandler.java:145)
	at org.intocps.orchestration.coe.json.CoeRequestHandler.doPost(CoeRequestHandler.java:70)
	at org.intocps.orchestration.coe.httpserver.NanoHTTPDJson$HTTPSession.processRequest(NanoHTTPDJson.java:335)
	at org.intocps.orchestration.coe.httpserver.NanoHTTPDJson$HTTPSession.run(NanoHTTPDJson.java:302)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NullPointerException
	at org.intocps.orchestration.coe.httpserver.Response.<init>(Response.java:58)
	at org.intocps.orchestration.coe.json.CoeRequestHandler.processInitialize(CoeRequestHandler.java:440)
	at org.intocps.orchestration.coe.json.CoeRequestHandler.handleRequest(CoeRequestHandler.java:145)
	at org.intocps.orchestration.coe.json.CoeRequestHandler.doPost(CoeRequestHandler.java:70)
	at org.intocps.orchestration.coe.httpserver.NanoHTTPDJson$HTTPSession.processRequest(NanoHTTPDJson.java:335)
	at org.intocps.orchestration.coe.httpserver.NanoHTTPDJson$HTTPSession.run(NanoHTTPDJson.java:302)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "Thread-1" java.lang.NullPointerException
	at org.intocps.orchestration.coe.httpserver.NanoHTTPDJson$HTTPSession.sendError(NanoHTTPDJson.java:355)
	at org.intocps.orchestration.coe.httpserver.NanoHTTPDJson$HTTPSession.processRequest(NanoHTTPDJson.java:342)
	at org.intocps.orchestration.coe.httpserver.NanoHTTPDJson$HTTPSession.run(NanoHTTPDJson.java:302)
	at java.lang.Thread.run(Thread.java:745)
```

based on the output it is unclear to me why this error is spawned and what is creating it. 

System info:

```
martin@mpc-ThinkPad-W530:~/COE_tester$ uname -a
Linux mpc-ThinkPad-W530 3.19.0-58-generic #64~14.04.1-Ubuntu SMP Fri Mar 18 19:05:43 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
martin@mpc-ThinkPad-W530:~/COE_tester$ java -version
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)
martin@mpc-ThinkPad-W530:~/COE_tester$ curl --version
curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smtp smtps telnet tftp 
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP
```

**Comment by ldcouto** [comment]
<a href="https://github.com/mpcagro"><img src="https://avatars.githubusercontent.com/u/17993540?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mpcagro](https://github.com/mpcagro)**
_Monday May 02, 2016 at 13:50 GMT_

----

Seems like the field:

"parameters":{
        "{b2ca94ea-3cd9-45a7-83b8-609f8c17fb68}.controller.amplitude":0.5
    },

cannot be empty in the config.json file

**Comment by CThuleHansen** [comment]
If this is still an issue for the new COE, then please reopen.
