### ISSUE TITLE
java.io.IOException: Unable to delete file: 73885\simulation.log

### ISSUE THREAD

**Issue by ldcouto** [into-cps/intocps-ui#108]
<a href="https://github.com/FlorianLapschies"><img src="https://avatars.githubusercontent.com/u/19324745?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [FlorianLapschies](https://github.com/FlorianLapschies)**
_Thursday May 12, 2016 at 14:25 GMT_
_Originally opened as https://github.com/into-cps/INTO-CPS_Application/issues/23_

----

At the end of a simulation the following exception is thrown:
```
java.io.IOException: Unable to delete file: 73885\simulation.log
        at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2279)
        at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653)
        at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535)
        at org.intocps.orchestration.coe.httpserver.RequestProcessors.processDestroy(RequestProcessors.java:271)
        at org.intocps.orchestration.coe.httpserver.CoeRequestHandler.destroy(CoeRequestHandler.java:99)
        at org.intocps.orchestration.coe.httpserver.CoeRequestHandler.handleRequest(CoeRequestHandler.java:91)
        at org.intocps.orchestration.coe.httpserver.NanoHTTPDImpl.serve(NanoHTTPDImpl.java:37)
        at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:840)
        at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:189)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by ldcouto** [comment]
<a href="https://github.com/lausdahl"><img src="https://avatars.githubusercontent.com/u/2575418?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [lausdahl](https://github.com/lausdahl)**
_Thursday May 19, 2016 at 10:52 GMT_

----

Hi Florian,

Can I get you to list the API calls you did up to and including the one where this happened so I can test it locally.

**Comment by ldcouto** [comment]
@FlorianLapschies what's the status of this? Are you still having this error?

**Comment by ldcouto** [comment]
So, I'm going to assume that this is not an issue anymore. Please reopen if necessary.
