### ISSUE TITLE
Closing down windows in the "wrong" order may yield stange errors

### ISSUE THREAD

**Issue by pglvdm** [into-cps/intocps-ui#126]
Uncaught Exception:
Error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: DialogHandler.js:39:18.
    at BrowserWindow.callIntoRenderer (/Users/pgl/Documents/TEMP/into-cps-app-1.1.0-darwin-x64/into-cps-app-1.1.0.app/Contents/Resources/electron.asar/browser/rpc-server.js:186:19)
    at emitOne (events.js:101:20)
    at BrowserWindow.emit (events.js:188:7)

**Comment by ldcouto** [comment]
I think we need to kill any sub-windows when the main one dies. That will get rid of this

**Comment by CThuleHansen** [comment]
Agreed.
