### ISSUE TITLE
Error loading 20-sim FMUs

### ISSUE THREAD

**Issue by richardpayne** [into-cps/intocps-ui#139]
Using COE version 0.1.0, I get the following error:

ERROR [NanoHttpd Request Processor (#1)] (RequestProcessors.java:185) - Internal error in initialization
java.lang.Exception: {uav}-C:\Users\Richard\Documents\INTO-CPS\INTO Git\case-study_uav_swarm\FMUs\UAV_Rep.fmu: Illegal character in opaque part at index 2: C:\Users\Richard\Documents\INTO-CPS\INTO Git\case-study_uav_swarm\FMUs\UAV_Rep.fmu
at org.intocps.orchestration.coe.json.InitializationMsgJson.getFmuFiles(InitializationMsgJson.java:163)
at org.intocps.orchestration.coe.httpserver.RequestProcessors.processInitialize(RequestProcessors.java:182)
at org.intocps.orchestration.coe.httpserver.RequestHandler.initialize(RequestHandler.java:280)
at org.intocps.orchestration.coe.httpserver.RequestHandler.handleRequest(RequestHandler.java:177)
at org.intocps.orchestration.coe.httpserver.NanoWSDImpl.serveHttp(NanoWSDImpl.java:36)
at fi.iki.elonen.NanoWSD.serve(NanoWSD.java:861)
at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:925)
at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
at java.lang.Thread.run(Unknown Source)
Caused by: java.net.URISyntaxException: Illegal character in opaque part at index 2: C:\Users\Richard\Documents\INTO-CPS\INTO Git\case-study_uav_swarm\FMUs\UAV_Rep.fmu
at java.net.URI$Parser.fail(Unknown Source)
at java.net.URI$Parser.checkChars(Unknown Source)
at java.net.URI$Parser.parse(Unknown Source)
at java.net.URI.<init>(Unknown Source)
at org.intocps.orchestration.coe.json.InitializationMsgJson.getFmuFiles(InitializationMsgJson.java:160)
... 8 more
Aug 03, 2016 4:47:03 PM fi.iki.elonen.NanoHTTPD$DefaultTempFileManager clear
WARNING: could not delete file 
java.lang.Exception: could not delete temporary file
at fi.iki.elonen.NanoHTTPD$DefaultTempFile.delete(NanoHTTPD.java:403)
at fi.iki.elonen.NanoHTTPD$DefaultTempFileManager.clear(NanoHTTPD.java:446)
at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:964)
at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
at java.lang.Thread.run(Unknown Source)

This is using the UAV Swarm case study (in development branch) and any Multi-model

**Comment by kgpierce** [comment]
Hi, seeing the full error message I just realised that this is the same as #136 which is fixed, but not in the release yet.
