### ISSUE TITLE
Whole numbers in initial step size

### ISSUE THREAD

**Issue by ldcouto** [into-cps/intocps-ui#164]
For variable step sizes, if you set an initial step that's a whole number, the COE dies with `initsize is not a double`. This happens even if you use say `1.0`. Is this restriction legitimate or an error? Seems like an error.

In any case, the simulation just hangs at 50%. It should switch to failed.

```
ERROR [NanoHttpd Request Processor (#1)] (RequestProcessors.java:201) - initsize is not a double
Oct 05, 2016 4:10:32 PM fi.iki.elonen.NanoHTTPD$DefaultTempFileManager clear
WARNING: could not delete file
java.lang.Exception: could not delete temporary file
        at fi.iki.elonen.NanoHTTPD$DefaultTempFile.delete(NanoHTTPD.java:403)
        at fi.iki.elonen.NanoHTTPD$DefaultTempFileManager.clear(NanoHTTPD.java:446)
        at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:964)
        at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by lausdahl** [comment]
fixed in release contained in 0.0.9
