### ISSUE TITLE
Examples Import Inconsistencies

### ISSUE THREAD

**Issue by ldcouto** [into-cps/intocps-ui#191]
There's something wrong with the examples import. It hangs in some circunstances.

According to @kgpierce, the UAV example gets stuck at 99%, then importing over the top again gets stuck So .project.json is not being downloaded. Console output:

```
C:\Users\ken\Downloads\into-cps-app-2.1.7-rc-win32-x64\resources\electron.asar\renderer\api\remote.…:178 Uncaught Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: ENOENT: no such file or directory, open 'C:\Users\ken\into-cps-projects\case-study_UAV\.project.json'
Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: ENOENT: no such file or directory, open 'C:\Users\ken\into-cps-projects\case-study_UAV\.project.json'
    at callFunction (C:\Users\ken\Downloads\into-cps-app-2.1.7-rc-win32-x64\resources\electron.asar\browser\rpc-server.js:222:11)
    at EventEmitter.<anonymous> (C:\Users\ken\Downloads\into-cps-app-2.1.7-rc-win32-x64\resources\electron.asar\browser\rpc-server.js:303:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at EventEmitter.<anonymous> (C:\Users\ken\Downloads\into-cps-app-2.1.7-rc-win32-x64\resources\electron.asar\browser\api\web-contents.js:165:13)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
ProjectFetcher.ts:125 exit code: 1
ProjectFetcher.ts:120 closing code: 1
internal/process/next_tick.js:103 Uncaught (in promise) 1
```

There's also the matter of imports when the underlying repository has already been checked out and is maybe in a different branch. We don't have an error here but the behaviour could use some clarification. Ken is suggesting a force checkout of master branch.

There is also   #180, but I'm not sure what the current status is on that.

**Comment by ldcouto** [comment]
Archiving for now. There are no resources to look at the importer at the moment. This is documented as a known issue in the release notes going forward.
