### ISSUE TITLE
configurable NEO4J port (instead of hard-coded 7474)

### ISSUE THREAD

**Issue by ldcouto** [into-cps/intocps-ui#296]
The traceability does not work if port 7474 is already occupied.

Starting the NEO4J server manually on a different port (17474) works, but then the Traceability Daemon does not connect to it, because port 7474 seems to be hard coded. The port must be made configurable (in the "Settings").

```
## -------------------------------------------------------------------------
2017-12-04 13:48:45.935+0000 ERROR Failed to start Neo4j on localhost:7474: Address localhost:7474 is already in use, cannot bind to it.
2017-12-04 13:48:45.935+0000 INFO  Stopping...
2017-12-04 13:48:46.037+0000 INFO  Stopped.
2017-12-04 13:48:46.037+0000 ERROR Failed to start Neo4j: Starting Neo4j failed:Address localhost:7474 is already in use, cannot bind to it. Starting Neo4j failed: Address localhost:7474 is already in use, cannot bind to it.
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Address localhost:7474 is already in use, cannot bind to it.
        at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:227)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:91)

        at org.neo4j.server.BlockingBootstrapper.start(BlockingBootstrapper.java:43)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:68)

        at org.neo4j.server.CommunityEntryPoint.start(CommunityEntryPoint.java:38)
Caused by: org.neo4j.helpers.PortBindException: Address localhost:7474 is already in use, cannot bind to it.
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Unknown Source)
        at sun.nio.ch.Net.bind(Unknown Source)
        at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
        at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)
        at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:321)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.server.Server.doStart(Server.java:366)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.neo4j.server.web.Jetty9WebServer.startJetty(Jetty9WebServer.java:363)
        at org.neo4j.server.web.Jetty9WebServer.start(Jetty9WebServer.java:178)
        at org.neo4j.server.AbstractNeoServer.startWebServer(AbstractNeoServer.java:326)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:218)
        ... 4 more
## -------------------------------------------------------------------------

```

**Comment by joshoell** [comment]
Good idea. We can simple make the port configurable. Unfortunately I do not have the time to implement that this year.

**Comment by ldcouto** [comment]
Alright, I'll move this to the enhancements archive.
