### ISSUE TITLE
[CLOSED] Java Unsatisfied Link Error Exception

### ISSUE THREAD

**Issue by ldcouto** [into-cps/intocps-ui#86]
<a href="https://github.com/richardpayne"><img src="https://avatars.githubusercontent.com/u/5848867?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [richardpayne](https://github.com/richardpayne)**
_Monday Feb 08, 2016 at 15:51 GMT_
_Originally opened as https://github.com/into-cps/INTO-CPS_Application/issues/1_

----

I get the following error when trying to launch the COE with 32-bit Java on Windows.

C:\Users\Richard\Desktop\threetank_co_3danim>"C:\Program Files (x86)\Java\jre1.8.0_73\bin\java.exe" -jar coe-0.0.1-SNAPSHOT-jar-with-dependencies.jar
COE(Command line options: [port]

 INFO [main] (CoeMain.java:29) - Checking native FMI support
Failed to load FMI API
ERROR [main] (CoeMain.java:35) - Failed to load FMI API
java.lang.UnsatisfiedLinkError: C:\Users\Richard\AppData\Local\Temp\jnifmuapi-Windows-x86\fmuapi.dll: Operation did not complete successfully because the file contains a virus or potentially unwanted software
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(Unknown Source)
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.lang.System.loadLibrary(Unknown Source)
        at org.intocps.fmi.jnifmuapi.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:61)
        at org.intocps.fmi.jnifmuapi.NativeFmu.<clinit>(NativeFmu.java:26)
        at org.intocps.fmi.jnifmuapi.Factory.checkApi(Factory.java:30)
        at org.intocps.orchestration.coe.CoeMain.main(CoeMain.java:31)

I also get a Windows Defender popup saying that Malwatre has been detected. 

Cheers, Richard

**Comment by ldcouto** [comment]
<a href="https://github.com/CThuleHansen"><img src="https://avatars.githubusercontent.com/u/3479481?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [CThuleHansen](https://github.com/CThuleHansen)**
_Wednesday Feb 10, 2016 at 06:59 GMT_

----

Hi Richard,
Can you try running the COE as administrator?

Cheers,
Casper

**Comment by ldcouto** [comment]
<a href="https://github.com/richardpayne"><img src="https://avatars.githubusercontent.com/u/5848867?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [richardpayne](https://github.com/richardpayne)**
_Wednesday Feb 10, 2016 at 09:59 GMT_

----

I have done this (I now have to use Java 8.74 32 bit as Windows 10 refuses to run 8.73 since yesterday), and now I get a new error. I am still warned about running the COE in 32 bit, but I can accept that and move one. 

The new error may be due to the 3DAnimation FMU:

C:\Users\Richard\Desktop\threetank_co_3danim>"C:\Program Files (x86)\Java\jre1.8.0_74\bin\java.exe" -jar coe-0.0.1-SNAPSHOT-jar-with-dependencies.jar
COE(Command line options: [port]

 INFO [main] (CoeMain.java:29) - Checking native FMI support
Now running on port 8082
Hit Enter to stop.

 INFO [Thread-1] (CoeRequestHandler.java:287) - Using Fixed-step size calculator with size = 0.02
[WaterTankController.fmu, WaterTanks1.fmu, WaterTanks2.fmu, 3DAnimationFMU.fmu]
[{8c4e810f-3df3-4a00-8276-176fa3c9f003}.controller.wt3_valve -> {25941611-1350-4ca2-8fe8-85d9193c14fd}.tank3.valveControl, {8c4e810f-3df3-4a00-8276-176fa3c9f003}.controller.wt3_valve -> {946f9503-6eb1-41de-8ad1-5e0b8fc5ee34}.3DAnimationFMU.animation.tank3.valve.control, {dcd729ec-423a-4a0d-8030-4c42a840abba}.tank1and2.Tank2OutFlow -> {25941611-1350-4ca2-8fe8-85d9193c14fd}.tank3.inFlow, {dcd729ec-423a-4a0d-8030-4c42a840abba}.tank1and2.Tank2OutFlow -> {946f9503-6eb1-41de-8ad1-5e0b8fc5ee34}.3DAnimationFMU.animation.tank2.outflow, {25941611-1350-4ca2-8fe8-85d9193c14fd}.tank3.level -> {8c4e810f-3df3-4a00-8276-176fa3c9f003}.controller.wt3_level, {25941611-1350-4ca2-8fe8-85d9193c14fd}.tank3.level -> {946f9503-6eb1-41de-8ad1-5e0b8fc5ee34}.3DAnimationFMU.animation.tank3.waterlevel, {dcd729ec-423a-4a0d-8030-4c42a840abba}.tank1and2.Tank1InFlow -> {946f9503-6eb1-41de-8ad1-5e0b8fc5ee34}.3DAnimationFMU.animation.tank1.inflow, {dcd729ec-423a-4a0d-8030-4c42a840abba}.tank1and2.Tank1WaterLevel -> {946f9503-6eb1-41de-8ad1-5e0b8fc5ee34}.3DAnimationFMU.animation.tank1.waterlevel, {dcd729ec-423a-4a0d-8030-4c42a840abba}.tank1and2.Tank2WaterLevel -> {946f9503-6eb1-41de-8ad1-5e0b8fc5ee34}.3DAnimationFMU.animation.tank2.waterlevel, {25941611-1350-4ca2-8fe8-85d9193c14fd}.tank3.Tank3OutFlow -> {946f9503-6eb1-41de-8ad1-5e0b8fc5ee34}.3DAnimationFMU.animation.tank3.outflow, {25941611-1350-4ca2-8fe8-85d9193c14fd}.tank3.puddle -> {946f9503-6eb1-41de-8ad1-5e0b8fc5ee34}.3DAnimationFMU.animation.drain.puddle]
[org.intocps.orchestration.coe.config.ModelParameter@6db05c, org.intocps.orchestration.coe.config.ModelParameter@1d03ea8]
 INFO [Thread-1] (CoeInitialize.scala:54) - loading fmus
TRACE [Thread-1] (CoeInitialize.scala:209) - Set({8c4e810f-3df3-4a00-8276-176fa3c9f003}.controller, {dcd729ec-423a-4a0d-8030-4c42a840abba}.tank1and2, {25941611-1350-4ca2-8fe8-85d9193c14fd}.tank3)
 INFO [Thread-1] (CoeInitialize.scala:213) - Outputs from: {8c4e810f-3df3-4a00-8276-176fa3c9f003}.controller = Set(wt3_valve)
 INFO [Thread-1] (CoeInitialize.scala:213) - Outputs from: {dcd729ec-423a-4a0d-8030-4c42a840abba}.tank1and2 = Set(Tank2OutFlow, Tank1InFlow, Tank1WaterLevel, Tank2WaterLevel)
 INFO [Thread-1] (CoeInitialize.scala:213) - Outputs from: {25941611-1350-4ca2-8fe8-85d9193c14fd}.tank3 = Set(level, Tank3OutFlow, puddle)
 INFO [Thread-1] (CoeInitialize.scala:218) - Inputs for: {25941611-1350-4ca2-8fe8-85d9193c14fd}.tank3
 INFO [Thread-1] (CoeInitialize.scala:220) -    {8c4e810f-3df3-4a00-8276-176fa3c9f003}.controller.wt3_valve --> valveControl
 INFO [Thread-1] (CoeInitialize.scala:220) -    {dcd729ec-423a-4a0d-8030-4c42a840abba}.tank1and2.Tank2OutFlow --> inFlow
 INFO [Thread-1] (CoeInitialize.scala:218) - Inputs for: {946f9503-6eb1-41de-8ad1-5e0b8fc5ee34}.3DAnimationFMU
 INFO [Thread-1] (CoeInitialize.scala:220) -    {25941611-1350-4ca2-8fe8-85d9193c14fd}.tank3.level --> animation.tank3.waterlevel
 INFO [Thread-1] (CoeInitialize.scala:220) -    {dcd729ec-423a-4a0d-8030-4c42a840abba}.tank1and2.Tank2WaterLevel --> animation.tank2.waterlevel
 INFO [Thread-1] (CoeInitialize.scala:220) -    {25941611-1350-4ca2-8fe8-85d9193c14fd}.tank3.Tank3OutFlow --> animation.tank3.outflow
 INFO [Thread-1] (CoeInitialize.scala:220) -    {dcd729ec-423a-4a0d-8030-4c42a840abba}.tank1and2.Tank2OutFlow --> animation.tank2.outflow
 INFO [Thread-1] (CoeInitialize.scala:220) -    {8c4e810f-3df3-4a00-8276-176fa3c9f003}.controller.wt3_valve --> animation.tank3.valve.control
 INFO [Thread-1] (CoeInitialize.scala:220) -    {dcd729ec-423a-4a0d-8030-4c42a840abba}.tank1and2.Tank1WaterLevel --> animation.tank1.waterlevel
 INFO [Thread-1] (CoeInitialize.scala:220) -    {25941611-1350-4ca2-8fe8-85d9193c14fd}.tank3.puddle --> animation.drain.puddle
 INFO [Thread-1] (CoeInitialize.scala:220) -    {dcd729ec-423a-4a0d-8030-4c42a840abba}.tank1and2.Tank1InFlow --> animation.tank1.inflow
 INFO [Thread-1] (CoeInitialize.scala:218) - Inputs for: {8c4e810f-3df3-4a00-8276-176fa3c9f003}.controller
 INFO [Thread-1] (CoeInitialize.scala:220) -    {25941611-1350-4ca2-8fe8-85d9193c14fd}.tank3.level --> wt3_level
warning: Function fmi2GetMaxStepsize not found in dll
warning: Function fmi2GetMaxStepsize not found in dll
warning: Function fmi2GetMaxStepsize not found in dll
--Launching with shared memory key: {8c4e810f-3df3-4a00-8276-176fa3c9f003}controller
Launching process: 'java' with arguments: 'java -jar crescendo-fmi-2.0.7-SNAPSHOT-jar-with-dependencies.jar -p {8c4e810f-3df3-4a00-8276-176fa3c9f003}controller' in folder 'C:\Users\Richard\AppData\Local\Temp\fmu-1455098131471\resources'
Process launched continuing main thread.
AnimationFrame::InitializeDLL(void)m_plotDLL->IsLoaded() == falsePlot Control could not be loaded.Starting Crescendo ShmServer with key: '{8c4e810f-3df3-4a00-8276-176fa3c9f003}controller'
DEBUG [main] (SharedMemory.java:27) - Loading library: lib/Windows-x86/sharedmemory.dll
DEBUG [main] (NativeLibraryLoader.java:37) - Extracting library from: lib/Windows-x86/sharedmemory.dll
java.nio.file.AccessDeniedException: C:\Users\Richard\AppData\Local\Temp\fmi-shm-Windows-x86\sharedmemory.dll
        at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsFileSystemProvider.implDelete(Unknown Source)
        at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(Unknown Source)
        at java.nio.file.Files.deleteIfExists(Unknown Source)
        at java.nio.file.Files.copy(Unknown Source)
        at org.intocps.fmi.jnifmuapi.NativeLibraryLoader.extractNativeLibrary(NativeLibraryLoader.java:101)
        at org.intocps.fmi.jnifmuapi.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:38)
        at org.intocps.java.fmi.shm.SharedMemory.<clinit>(SharedMemory.java:31)
        at org.intocps.java.fmi.service.ProtocolDriver.<init>(ProtocolDriver.java:20)
        at org.crescendo.fmi.ShmServer.main(ShmServer.java:23)
ERROR [main] (SharedMemory.java:35) - Faild to load native Library file: lib/Windows-x86/sharedmemory.dll
java.io.FileNotFoundException: Unable to find the native lib: lib/Windows-x86/sharedmemory.dll
        at org.intocps.fmi.jnifmuapi.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:42)
        at org.intocps.java.fmi.shm.SharedMemory.<clinit>(SharedMemory.java:31)
        at org.intocps.java.fmi.service.ProtocolDriver.<init>(ProtocolDriver.java:20)
        at org.crescendo.fmi.ShmServer.main(ShmServer.java:23)
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.intocps.java.fmi.service.ProtocolDriver.<init>(ProtocolDriver.java:20)
        at org.crescendo.fmi.ShmServer.main(ShmServer.java:23)
Caused by: java.lang.reflect.UndeclaredThrowableException
        at org.intocps.java.fmi.shm.SharedMemory.<clinit>(SharedMemory.java:36)
        ... 2 more
Caused by: java.io.FileNotFoundException: Unable to find the native lib: lib/Windows-x86/sharedmemory.dll
        at org.intocps.fmi.jnifmuapi.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:42)
        at org.intocps.java.fmi.shm.SharedMemory.<clinit>(SharedMemory.java:31)
        ... 2 more
No 3D plot initialize yetExecution protection violation
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00000000, pid=7284, tid=10952
#
# JRE version: Java(TM) SE Runtime Environment (8.0_74-b02) (build 1.8.0_74-b02)
# Java VM: Java HotSpot(TM) Client VM (25.74-b02 mixed mode windows-x86 )
# Problematic frame:
# C  0x00000000
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\Richard\Desktop\threetank_co_3danim\hs_err_pid7284.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

**Comment by ldcouto** [comment]
<a href="https://github.com/richardpayne"><img src="https://avatars.githubusercontent.com/u/5848867?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [richardpayne](https://github.com/richardpayne)**
_Wednesday Feb 10, 2016 at 10:03 GMT_

----

Ignore that! :) That was my fault in being stupid and running the COE from the wrong directory.

The COE seems to work ok now when bypassing the Windows security issues. I guess that this should still be resolved though.

**Comment by ldcouto** [comment]
<a href="https://github.com/CThuleHansen"><img src="https://avatars.githubusercontent.com/u/3479481?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [CThuleHansen](https://github.com/CThuleHansen)**
_Wednesday Feb 10, 2016 at 10:05 GMT_

----

Hi Richard,
That happens :)
Yes, it should definitely be resolved in the future, and it will be added to the list.

Before I close this  - It works when running as administrator?
