### ISSUE TITLE
[CLOSED] AccessDeniedException

### ISSUE THREAD

**Issue by ldcouto** [into-cps/intocps-ui#93]
<a href="https://github.com/richardpayne"><img src="https://avatars.githubusercontent.com/u/5848867?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [richardpayne](https://github.com/richardpayne)**
_Tuesday Mar 22, 2016 at 16:40 GMT_
_Originally opened as https://github.com/into-cps/INTO-CPS_Application/issues/8_

----

When running a co-simulation using the INTO-CPS COE I get an AccessDeniedException. I am not sure what is causing this!

java.nio.file.AccessDeniedException: C:\Users\Richard\AppData\Local\Temp\fmi-shm-Windows-amd64\sharedmemory.dll
at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
at sun.nio.fs.WindowsFileSystemProvider.implDelete(Unknown Source)
at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(Unknown Source)
at java.nio.file.Files.deleteIfExists(Unknown Source)
at java.nio.file.Files.copy(Unknown Source)
at org.intocps.fmi.jnifmuapi.NativeLibraryLoader.extractNativeLibrary(NativeLibraryLoader.java:101)
at org.intocps.fmi.jnifmuapi.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:38)
at org.intocps.java.fmi.shm.SharedMemory.(SharedMemory.java:31)
at org.intocps.java.fmi.service.ProtocolDriver.(ProtocolDriver.java:20)
at org.crescendo.fmi.ShmServer.main(ShmServer.java:23)
ERROR main - Faild to load native Library file: lib/Windows-amd64/sharedmemory.dll
java.io.FileNotFoundException: Unable to find the native lib: lib/Windows-amd64/sharedmemory.dll
at org.intocps.fmi.jnifmuapi.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:42)
at org.intocps.java.fmi.shm.SharedMemory.(SharedMemory.java:31)
at org.intocps.java.fmi.service.ProtocolDriver.(ProtocolDriver.java:20)
at org.crescendo.fmi.ShmServer.main(ShmServer.java:23)
Exception in thread "main" java.lang.ExceptionInInitializerError
at org.intocps.java.fmi.service.ProtocolDriver.(ProtocolDriver.java:20)
at org.crescendo.fmi.ShmServer.main(ShmServer.java:23)
Caused by: java.lang.reflect.UndeclaredThrowableException
at org.intocps.java.fmi.shm.SharedMemory.(SharedMemory.java:36)
... 2 more
Caused by: java.io.FileNotFoundException: Unable to find the native lib: lib/Windows-amd64/sharedmemory.dll
at org.intocps.fmi.jnifmuapi.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:42)
at org.intocps.java.fmi.shm.SharedMemory.(SharedMemory.java:31)
... 2 more

**Comment by ldcouto** [comment]
<a href="https://github.com/CThuleHansen"><img src="https://avatars.githubusercontent.com/u/3479481?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [CThuleHansen](https://github.com/CThuleHansen)**
_Monday Apr 04, 2016 at 10:12 GMT_

----

Is this related to #15 ?

**Comment by ldcouto** [comment]
<a href="https://github.com/CThuleHansen"><img src="https://avatars.githubusercontent.com/u/3479481?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [CThuleHansen](https://github.com/CThuleHansen)**
_Monday Apr 04, 2016 at 11:43 GMT_

----

Do you have any data so I can reproduce?

**Comment by ldcouto** [comment]
<a href="https://github.com/lausdahl"><img src="https://avatars.githubusercontent.com/u/2575418?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [lausdahl](https://github.com/lausdahl)**
_Thursday May 19, 2016 at 10:51 GMT_

----

Hi @richardpayne can yo try updating the overture-fmu export and check if this still happens. I just added a fix which should create a new temp folder for each process and delete it on exit.

I will close the issue so please re-open if it happens again.
