### ISSUE TITLE
[CLOSED] NullPointerException when initialising model

### ISSUE THREAD

**Issue by ldcouto** [into-cps/intocps-ui#94]
<a href="https://github.com/richardpayne"><img src="https://avatars.githubusercontent.com/u/5848867?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [richardpayne](https://github.com/richardpayne)**
_Tuesday Mar 22, 2016 at 17:23 GMT_
_Originally opened as https://github.com/into-cps/INTO-CPS_Application/issues/9_

----

During the initialisation of the COE I get the following exception. It appears to be related to setting the initial values as identified in the ModelDescription file.

 INFO [Thread-2] (BasicInitializer.java:76) - Entering Initialization
 INFO [Thread-2] (BasicInitializer.java:77) - Running Initialization for component: {guid}.controller
TRACE [Thread-2] (BasicInitializer.java:171) - Setting Real Map: {16=0.0, 17=0.0, 6=0.0, 7=0.0, 8=0.0, 9=0.0, 10=0.0, 11=0.0, 12=0.0, 13=0.0, 14=0.0, 15=0.0}
TRACE [Thread-2] (Util.java:92) - setRaw with comp: {guid}.controller, type: Real, indices: [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17], values: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
Exception in thread "Thread-0" java.lang.NullPointerException
        at org.crescendo.fmi.CrescendoFmu.SetReal(CrescendoFmu.java:405)
        at org.intocps.java.fmi.service.ProtocolDriver.run(ProtocolDriver.java:106)
        at java.lang.Thread.run(Unknown Source)

**Comment by ldcouto** [comment]
<a href="https://github.com/richardpayne"><img src="https://avatars.githubusercontent.com/u/5848867?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [richardpayne](https://github.com/richardpayne)**
_Friday Apr 01, 2016 at 11:11 GMT_

----

Correction: this appears post-initialisation, when attempting to start simulation. The error does not always appear for the same model (I had experienced this repeatedly, closed and reopened the command line and then the simulation started fine).

**Comment by ldcouto** [comment]
<a href="https://github.com/CThuleHansen"><img src="https://avatars.githubusercontent.com/u/3479481?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [CThuleHansen](https://github.com/CThuleHansen)**
_Monday Apr 04, 2016 at 10:12 GMT_

----

Do you have any data for me, so I can reproduce?

**Comment by ldcouto** [comment]
<a href="https://github.com/lausdahl"><img src="https://avatars.githubusercontent.com/u/2575418?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [lausdahl](https://github.com/lausdahl)**
_Thursday Apr 28, 2016 at 09:29 GMT_

----

@richardpayne please provide the complete model otherwise we will close this by May 6, 2016

**Comment by ldcouto** [comment]
<a href="https://github.com/richardpayne"><img src="https://avatars.githubusercontent.com/u/5848867?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [richardpayne](https://github.com/richardpayne)**
_Thursday Apr 28, 2016 at 10:32 GMT_

----

I've not received this error for a while - I'll close it.
