### ISSUE TITLE
[CLOSED] Shared Memory Temp file not released by COE

### ISSUE THREAD

**Issue by ldcouto** [into-cps/intocps-ui#98]
<a href="https://github.com/richardpayne"><img src="https://avatars.githubusercontent.com/u/5848867?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [richardpayne](https://github.com/richardpayne)**
_Friday Apr 01, 2016 at 11:38 GMT_
_Originally opened as https://github.com/into-cps/INTO-CPS_Application/issues/15_

----

When I need to quit the COE in Windows (e.g. when simulation fails) the COE does not seem to release a sharedmemory.dll resulting in the exception below. The only way to get around this issue is to remove the file (in C:\Users\Richard\AppData\Local\Temp\).

TRACE [Thread-1] (CoeRequestHandler.java:356) - Initialization completed obtained the following logging categories: {{guid}.controller=[logAll, logError, logFmiCall, Protocol, VdmOut, VdmErr, Error], {9737bfcb-3243-4f09-ac5c-9ac4872e3d94}.sensor1=[], {09870916-25e8-4dd6-9f73-e77f5cad4edb}.sensor2=[], {67b3ebec-dced-4ebb-8cdd-4011d79f116b}.body=[]}
DEBUG [main] (SharedMemory.java:27) - Loading library: lib/Windows-amd64/sharedmemory.dll
DEBUG [main] (NativeLibraryLoader.java:37) - Extracting library from: lib/Windows-amd64/sharedmemory.dll
java.nio.file.AccessDeniedException: C:\Users\Richard\AppData\Local\Temp\fmi-shm-Windows-amd64\sharedmemory.dll
        at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsFileSystemProvider.implDelete(Unknown Source)
        at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(Unknown Source)
        at java.nio.file.Files.deleteIfExists(Unknown Source)
        at java.nio.file.Files.copy(Unknown Source)
        at org.intocps.fmi.jnifmuapi.NativeLibraryLoader.extractNativeLibrary(NativeLibraryLoader.java:101)
        at org.intocps.fmi.jnifmuapi.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:38)
        at org.intocps.java.fmi.shm.SharedMemory.<clinit>(SharedMemory.java:31)
        at org.intocps.java.fmi.service.ProtocolDriver.<init>(ProtocolDriver.java:20)
        at org.crescendo.fmi.ShmServer.main(ShmServer.java:23)
ERROR [main] (SharedMemory.java:35) - Faild to load native Library file: lib/Windows-amd64/sharedmemory.dll
java.io.FileNotFoundException: Unable to find the native lib: lib/Windows-amd64/sharedmemory.dll
        at org.intocps.fmi.jnifmuapi.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:42)
        at org.intocps.java.fmi.shm.SharedMemory.<clinit>(SharedMemory.java:31)
        at org.intocps.java.fmi.service.ProtocolDriver.<init>(ProtocolDriver.java:20)
        at org.crescendo.fmi.ShmServer.main(ShmServer.java:23)
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.intocps.java.fmi.service.ProtocolDriver.<init>(ProtocolDriver.java:20)
        at org.crescendo.fmi.ShmServer.main(ShmServer.java:23)
Caused by: java.lang.reflect.UndeclaredThrowableException
        at org.intocps.java.fmi.shm.SharedMemory.<clinit>(SharedMemory.java:36)
        ... 2 more
Caused by: java.io.FileNotFoundException: Unable to find the native lib: lib/Windows-amd64/sharedmemory.dll
        at org.intocps.fmi.jnifmuapi.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:42)
        at org.intocps.java.fmi.shm.SharedMemory.<clinit>(SharedMemory.java:31)
        ... 2 more

**Comment by ldcouto** [comment]
<a href="https://github.com/CThuleHansen"><img src="https://avatars.githubusercontent.com/u/3479481?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [CThuleHansen](https://github.com/CThuleHansen)**
_Monday Apr 04, 2016 at 09:57 GMT_

----

So this is probably related to #8 as well?

**Comment by ldcouto** [comment]
<a href="https://github.com/richardpayne"><img src="https://avatars.githubusercontent.com/u/5848867?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [richardpayne](https://github.com/richardpayne)**
_Monday Apr 04, 2016 at 10:07 GMT_

----

Ah, sorry - yes. I didn't realise I'd added this one earlier.
