### ISSUE TITLE
[CLOSED] Overture/Crescendo/Destecs simulator not terminating at end of simulation

### ISSUE THREAD

**Issue by ldcouto** [into-cps/intocps-ui#99]
<a href="https://github.com/richardpayne"><img src="https://avatars.githubusercontent.com/u/5848867?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [richardpayne](https://github.com/richardpayne)**
_Friday Apr 01, 2016 at 12:13 GMT_
_Originally opened as https://github.com/into-cps/INTO-CPS_Application/issues/16_

----

At the end of a simulation I am getting the following exception:

 INFO [Thread-7] (CoeSimulator.scala:179) - DoStep at: 14.995000000000944 Completed with: ok
 INFO [Thread-7] (CoeSimulator.scala:182) - Freeing serilized states from: 14.995000000000944
TRACE [Thread-7] (CoeSimulator.scala:185) - Map({guid}.controller -> Time 14.995000000000944, StateId null, Derivatives null, StateMap(xOut -> 0.0, servo_right_out -> 0.0, theta -> 0.0, yOut -> 0.0, servo_left_out -> 0.0, zOut -> 0.0), {9737bfcb-3243-4f09-ac5c-9ac4872e3d94}.sensor1 -> Time 14.995000000000944, StateId null, Derivatives null, StateMap(lf_1_sensor_position_y -> 0.0, lf_1_sensor_reading -> 255.00000000000006, lf_1_sensor_position_x -> 0.0), {09870916-25e8-4dd6-9f73-e77f5cad4edb}.sensor2 -> Time 14.995000000000944, StateId null, Derivatives null, StateMap(lf_1_sensor_reading -> 255.00000000000006, lf_1_sensor_position_x -> -0.1, lf_1_sensor_position_y -> -0.1))
terminate
org.destecs.protocol.exceptions.RemoteSimulationException: Could not stop the scheduler
        at org.destecs.vdm.SimulationManager.stopSimulation(SimulationManager.java:1170)
        at org.crescendo.fmi.CrescendoFmu.Terminate(CrescendoFmu.java:170)
        at org.intocps.java.fmi.service.ProtocolDriver.run(ProtocolDriver.java:115)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at org.overture.interpreter.debug.DBGPReaderV2.writeCoverage(DBGPReaderV2.java:2048)
        at org.destecs.vdm.SimulationManager.stopSimulation(SimulationManager.java:1135)
        ... 3 more
Error in Terminate: Could not stop the scheduler
ERROR [Thread-7] (CoeRequestHandler.java:246) - Error in simulation
org.intocps.orchestration.coe.AbortSimulationException: Setup Experiment failed
        {guid}.controller did not successfully complete. It returned: Fatal
        at org.intocps.orchestration.coe.scala.CoeObject$.handleCallResults(CoeObject.scala:100)
        at org.intocps.orchestration.coe.scala.CoeObject$.fmiCallAll(CoeObject.scala:86)
        at org.intocps.orchestration.coe.scala.CoeSimulator$.simulate(CoeSimulator.scala:95)
        at org.intocps.orchestration.coe.scala.Coe.simulate(Coe.scala:49)
        at org.intocps.orchestration.coe.json.CoeRequestHandler.processSimulate(CoeRequestHandler.java:241)
        at org.intocps.orchestration.coe.json.CoeRequestHandler.handleRequest(CoeRequestHandler.java:117)
        at org.intocps.orchestration.coe.json.CoeRequestHandler.doPost(CoeRequestHandler.java:59)
        at org.intocps.orchestration.coe.httpserver.NanoHTTPDJson$HTTPSession.processRequest(NanoHTTPDJson.java:340)
        at org.intocps.orchestration.coe.httpserver.NanoHTTPDJson$HTTPSession.run(NanoHTTPDJson.java:306)
        at java.lang.Thread.run(Unknown Source)

The model and config are in Dropbox here: https://www.dropbox.com/sh/kxtrj48gkeg1s5e/AAAsXO4Ka6Su-Nad1I5qnoKla?dl=0

**Comment by ldcouto** [comment]
<a href="https://github.com/richardpayne"><img src="https://avatars.githubusercontent.com/u/5848867?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [richardpayne](https://github.com/richardpayne)**
_Friday Apr 01, 2016 at 12:39 GMT_

----

Oddly, I realised there was a small error in my VDM-RT model (an instance variable was being used by one class which didn't exist (System`servo_left_output - that variable was also listed in the model description file as an output variable).

**Comment by ldcouto** [comment]
<a href="https://github.com/CThuleHansen"><img src="https://avatars.githubusercontent.com/u/3479481?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [CThuleHansen](https://github.com/CThuleHansen)**
_Monday Apr 04, 2016 at 10:15 GMT_

----

Does it work now after you fixed the error in your VDM-RT model?

**Comment by ldcouto** [comment]
<a href="https://github.com/richardpayne"><img src="https://avatars.githubusercontent.com/u/5848867?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [richardpayne](https://github.com/richardpayne)**
_Monday Apr 04, 2016 at 10:21 GMT_

----

It did, however the error in the COE gave no indication that the VDM-RT model was an issue - could the error messages be improved in any way?

**Comment by ldcouto** [comment]
<a href="https://github.com/CThuleHansen"><img src="https://avatars.githubusercontent.com/u/3479481?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [CThuleHansen](https://github.com/CThuleHansen)**
_Monday Apr 04, 2016 at 10:22 GMT_

----

Yes. That is an objective, so it is on the list :)

**Comment by ldcouto** [comment]
<a href="https://github.com/CThuleHansen"><img src="https://avatars.githubusercontent.com/u/3479481?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [CThuleHansen](https://github.com/CThuleHansen)**
_Monday Apr 04, 2016 at 10:22 GMT_

----

e.g. here: #10
